neutralinojs/neutralinojs-cli

src/commands/build.js
src/modules/bundler.js

It was bugging me that the output from `neu build` was hidden during run, forcing me to run the underlying `npm run build` command to see full output. So I added verbosity as an option. It can be used like:
```
neu build -v
```
or
```
neu build -verbose
```
Additionally, rather than writing errors and standard output via `console.log`, I modified the build function to pipe the streams directly, thus preserving any color information that is produced by the underlying build command.

Added --verbose option to neu build

---

src/modules/bundler.js
src/modules/downloader.js
src/modules/runner.js

`downloader.js` changes:
- After downloading, create a `bin` directory
- Copy the binary files to the newly-created `bin` directory
`bundler.js` changes: 
- Remove unused import
- Adjust paths to support new ones and legacy ones
`runner.js` changes:
- Adjust paths to support new ones and legacy ones
- Fix 777 chmod which could lead to vulnerabilities
- Remove unusued import
**What works**  
[x] Creating project  
[x] Bundling & running  
[ ] Using the run command (Can't use `--load-dir-res`)
[ ] Using the listen command (Same error as ^)
Error message  
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
what():  [json.exception.type_error.302] type must be string, but is null
Aborted (core dumped)
```

[Need Help] Refactoring: Put the downloaded binaries in a bin directory and don't rename them to the binaryName

---

src/modules/runner.js

This change makes neu-cli much more developer friendly. It took me hours to figure out why my extension wasn't working. To debug it I would have to quit my app over and over to see the stdout of the extension process.
This PR switches from using exec to spawn so that the child process can inherit the stdio from the parent process. This causes extensions stdout to appear in real time (and in color) when running `neu run`.
Having this change would have saved me 5+ hours of banging my head against the wall trying to get my extension set up 🤦 
Not having this made it extremely difficult to debug https://github.com/neutralinojs/neutralinojs/issues/801 and https://github.com/neutralinojs/neutralinojs/issues/790

feat: output colored stdout in realtime

---

src/modules/creator.js

- If there exits an app with same name as new one being created, throw error and end `create` process.
- fixes #122 
cc : @shalithasuranga

Throw error in case app name already exists in current directory

---

src/modules/bundler.js
src/modules/downloader.js
src/utils.js

Both ``bundler`` and ``downloader`` module had the same function written under different names.
Shifted logic of clearing Cache to ``utils.js`` under the common name ``clearCache()``

Create a common clearCache function in utils.js

---

src/modules/bundler.js
src/modules/downloader.js
src/utils.js

Renamed temporary directories to ``.tmp`` to make it consistent with other parts of the framework. (suggested by @shalithasuranga [here](https://discord.com/channels/869948661084340265/926731022316478474/964162508132859956))

Make temporary directories consistent with the other parts of the framework

---

src/plugins/pluginloader.js

``--save`` is redundant with npm 5.0.0 (or above) which was released in 2017 (5 years ago).

Remove redundant --save in pluginloader module

---

src/modules/bundler.js

- Currently, `neu build --copy-storage` throws no error in case the `.storage` directory is not found.
- Improved error handling in the following pull request.

Add error handling to neu build --copy-storage command

---

spec/run.spec.js

@shalithasuranga Need discussion on how to test commands that open neutralinojs app. The further tests gets halted in case a command runs to open a neutralinojs app. We can however use OS specific commands to get the app closed to check for expected output. This implementation will however require different tests for different operating systems.
I have checked out tests that run on the main framework. Its very clear that these tests become redundant here. So I don't find a point in adding tests here. However I created a file for `neu run` tests to keep things consistent and in case new tests need to be added later. Please let me know in this regard.

Initial test for neu run command

---

package.json
src/modules/downloader.js

Replaced `unzipper` module with `decompress` because it:
- corrupts extracted files with Node 18+
- has lot of open issues, including [this one](https://github.com/neutralinojs/neutralinojs-cli/issues/200) related to decompression corruption

Replace unzipper module with decompress

---

src/constants.js

This PR follows [my other one](https://github.com/neutralinojs/neutralinojs/pull/1109) in [neutralinojs](https://github.com/neutralinojs/neutralinojs) that embeds WebView2Loader lib statically in Windows build.
WebView2Loader.dll won't be copied to dist folder anymore...

Removed WebView2Loader.dll from dependencies

---

src/modules/websocket.js

Because some OSes, especially windows, tend to use the ipv6 version of the loopback address (::1), which does not work with the neutralino server, and some versions of NodeJS (>= 18) do resolve localhost addresses using the hosts config of the OS.
In response to the issue #208

Use ipv4 loopback address

---

src/modules/frontendlib.js

Fix for #223
Tested locally with my app.

Fix waiting for frontendlib app port

---

src/modules/frontendlib.js

Issue: https://github.com/neutralinojs/neutralinojs-cli/commit/18a2fed5ffcee2e5d43cbded40b5e61c971a75aa seems to have made it impossible for me to use frontend lib development with Vite. Even though port 5173 is connected, it just says "application will be launched when .. is ready" and eventually gives up.
Solution: Check `localhost` instead. The concept works in my tests with the library.

Fix behavior with vite's dev server

---

src/modules/frontendlib.js

So the way Node works is it ends the process successfully when nothing is currently running. Even if the main thread is awaiting a promise, if no work is being done, it ends the process.
We have it currently set up so that we await frontend commands. However, if the command isn't found, we never `resolve` or `reject` it. We just return from the Promise, leaving it hanging. This makes Node exit, which heavily confused me.
This makes it so that it doesn't return a Promise unless it finds the command. This lets it just continue on if the command isn't set up.
If this is merged, this will fix a bug that's blocking me from building my app.

Don't kill the process when a command isn't found

---

src/modules/filewatcher.js
src/modules/frontendlib.js
src/plugins/pluginloader.js
src/utils.js

Resolves: neutralinojs/neutralino.js#71
This PR removes optional chaining from the codebase as our current code does not support old version of node.
Alternatively, we could use traspilers to resolve this issue while maintaining out modern codebase

removing optional chaining

---

src/modules/frontendlib.js

The change fixes an error that forces the use of the IPv6 protocol when querying the `cli.frontendLibrary.devUrl`.
If the IPv6 protocol cannot be disabled on the developer system, you can now work around this by using `"devUrl": "http://127.0.0.1:<port>"`. This was not possible before.
Please include the fix in your code. Thank you very much!

fix: Use configured host for waiting

---

spec/build.spec.js
src/commands/build.js
src/modules/bundler.js

closes #178 
Uses `dist` folder as default build directory
updated `build.spec` file.
pr for updated docs has been made [#306](https://github.com/neutralinojs/neutralinojs.github.io/pull/306)

Dynamic build paths

---

bin/neu.js
src/constants.js
src/modules/creator.js
src/modules/downloader.js

right now we dont have a check before downloading the zip to determine if a template is a valid template or not, and the app exits with error not telling the actual issue, I have added a check before downloading the template if `neutralino.config.json` file exists in root directory of the template repository or not to determine if the template is valid or not.
Previous Error
Current Error

feat: Check Template Validity before downloading

---

src/commands/build.js

Resolves: #258 
This PR makes it optional to remove the current build in the `neu build` command

Making clearing the current build in the `neu build` command optional

---

src/modules/frontendlib.js

Some frontend libraries like react take quite a while to spin up their dev server.
On some lower-end machines, it may even take more than 10 seconds.
To avoid this issue, I have added a new property under `config.cli.frontendLibrary.timeout` which allows you to specify an amount of miliseconds to wait for the dev server to spin up, thus overriding the default of 10 seconds.
This modification does not break compatibility, as it will still use 10 seconds if the option is not specified.

Add configurable timeout

---

src/commands/run.js

The dev server(frontend framework) is ran before the HTML file is patched with the new url of the globals file, resulting in: "Failed to load resource."
I'm not sure if I'm breaking anything by re-ordering the function invocation, but it seems to work for me.

Patch HTML file before starting dev server

---

package-lock.json
package.json
src/modules/bundler.js

Closes #275.
TL;DR: Allow using `neu build` with [Bun](https://bun.sh/) as node.js package runner.
Observed side effects: 
1. Zipping an empty neutralino app (made by `neu create sausage`) is roughly twice as faster. Good!
<details> <summary>Before/After</summary>
Before:<br/>
After:<br/>
</details>
2. The zip file is a _smidgen_ larger. (5 230 417 --> 5 247 436 bytes.) This is due to `zip-lib` not having any compression options  you can change.

:zap: Replace `archiver` with `zip-lib`

---

spec/.gitignore
src/commands/run.js
src/modules/bundler.js
src/modules/creator.js
src/modules/frontendlib.js
src/modules/projectRunner.js

Supported to init, run, build Neutralino Apps with project runner
- supports neu config parameters like so under cli
```json
"projectRunner": {
"projectPath": "/",
"buildPath": "./node-src/dist/",
"initCommand": "npm run runner:install",  
"devCommand": "npm run runner:start",     
"buildCommand": "npm run runner:build"
}
```
- `initCommand`, `devCommand`, `buildCommand` are run inside root of the Neu App
- could not understand the need of `type` attribute so did not include it
Todo: (in this [repo](https://github.com/neutralinojs-community/node-neutralino))
- add logic for running frontend library
- run binaries with new name when in build mode

Feat: support project runner

---

src/modules/hostproject.js

runApp method was not being used anywhere, since we are now running the app with hostProject.runCommand method.

chore: Remove unused process module import in hostproject.js

---

src/modules/downloader.js

A Mac user of ct.js reported that `npx @neutralinojs/neu create neuTestApp` downloaded binaries without the `+x` flags, which lead to `EPERM` errors or `Executable not found in $PATH` when run through other tools. Though I myself could not replicate it in a Mac VM, I suppose it is due to some security measure in newer macOS versions.
This PR adds a simple fs.chmodSync call on every non-windows binary when run on system other than Windows to make sure the executables have the right execution flags.
It also makes a function-less change to regEx statements in the code so VSCode's syntax highlighter doesn't break. (`<pattern>{N,M}` are used for quantifiers and ir seems that VSCode tokenizer detects any `{}` pair as one.)

:zap: Make sure Neutralino binaries have the right permissions

---

package-lock.json
package.json

fixes #287 
Moved outdated ``spawn-command`` dependency from ``0.0.2`` to ``1.0.0`` in ``package.json`` and ``package-lock.json``

bumped spawn-process from 0.0.2 to 1.0.0

---

src/commands/build.js
src/modules/bundler.js
src/modules/config.js

neu build now can specify neutralino.config.json by using --neu-json such as 
`neu build --neu-json neutralino.config_zhiyuan.json`
I have test it and the execute metadata  also is correct
---
Hope my work can help some guys.

neu build support specify neutralino.config.json

---

src/commands/run.js

Fixes #279
This PR addresses an issue in the Neutralinojs CLI where arguments containing spaces (e.g., file paths) were being split into multiple parameters. This is particularly problematic when using the `neu run` command with arguments like `--file="path with spaces.txt"`, which were incorrectly processed into separate arguments.
* Modified the argument parsing logic in the `run.js` file to properly handle parameters with spaces.
* Ensured that all arguments after `--` are treated as a single string, preserving spaces where needed.
* The PR introduces logic to properly join the arguments passed after `--` into a single string, ensuring that the entire argument, including paths with spaces, is passed correctly to the application.
* Created a test Neutralinojs project and used the …

Fix argument handling with spaces in neu run

---

src/modules/bundler.js

Fixes #231 by @hypherionmc 
This PR adds support for renaming the macOS build output folder to `.app` when neu build runs. The behavior is configurable via a new option in `neutralino.config.json`.
Currently, after running neu build, the macOS build outputs a folder named:
* `MyApp-mac_x64`
* `MyApp-mac_arm64`
* `MyApp-mac_universal`
This is not in the expected .app format, which can cause confusion and inconvenience for users.
* Introduced a new config option in neutralino.config.json
```
{
"cli": {
"macOutputAsAppBundle": true
}
}
```
* If `macOutputAsAppBundle` is enabled, the output folder will be renamed to `.app`.
* Supports all three architectures (mac_x64, mac_arm64, mac_universal).
* Prevents overwriting issues by preserving separate .app files for each architecture.

Fixes: Rename macOS output folder to .app in neu build

---

package-lock.json
package.json
src/commands/build.js
src/constants.js
src/modules/bundler.js

Hi! With this PR I want to finish the new `Single-File` build mode, embedding the `resources.neu` inside each binary using `postject`. I opened another [`PR #402`](https://github.com/neutralinojs/neutralinojs.github.io/pull/402) at the website with documentation; you can check it if you want.
First of all, I created an [example](https://github.com/IsmaCortGtz/neutralino-features-samples/tree/feature/portable) repository building with GitHub Actions; you can download the results [here](https://github.com/IsmaCortGtz/neutralino-features-samples/releases/tag/feat-portable). I can only test in `linux_x64` and `win_x64`, so any feedback about any other platform/architecture is very appreciated.  =)
The new `--embed-resources` flag is under the build command, so it can be used with `neu build …

feat: Add support for embedding resources in the build process
